#!/usr/bin/env python3
"""
Push an agent-status dashboard to the LilyGo e-paper display.

Usage:
    # Simple — pass agent status as key=value pairs
    ./dashboard.py --agent "pi=idle,2m" --agent "claude=thinking,12s"

    # From a JSON file (e.g. generated by another agent)
    cat agents.json | ./dashboard.py --input -

    # One-liner
    ./dashboard.py --title AGENTS \
        --agent "pi-coding,idle,2m ago" \
        --agent "claude,thinking,47s ago" \
        --stats "tokens=1.2M" "cost=\$2.41"
"""

import argparse
import json
import os
import sys
import urllib.request
import urllib.error
import datetime

DEFAULT_IP = os.environ.get("LILYGO_IP", "10.0.0.189")
URL = f"http://{DEFAULT_IP}/dashboard"


def push(data: dict) -> bool:
    payload = json.dumps(data).encode()
    req = urllib.request.Request(
        URL,
        data=payload,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status == 200:
                print(f"✓ Dashboard sent to http://{DEFAULT_IP}", file=sys.stderr)
                return True
            else:
                print(f"✗ Server returned {resp.status}", file=sys.stderr)
                return False
    except urllib.error.URLError as e:
        print(f"✗ Could not reach {DEFAULT_IP}: {e.reason}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Push dashboard to e-paper")
    parser.add_argument("--title", default="AGENTS")
    parser.add_argument("--subtitle", default=datetime.datetime.now().strftime("%H:%M"))
    parser.add_argument(
        "--agent",
        action="append",
        default=[],
        help='Agent entry: "name,status,time" (can repeat)',
    )
    parser.add_argument(
        "--stat",
        action="append",
        default=[],
        help='Stat pair: "label=value" (can repeat)',
    )
    parser.add_argument(
        "--queue",
        action="append",
        default=[],
        help='Queue item: "• some task" (can repeat)',
    )
    parser.add_argument(
        "--input",
        type=argparse.FileType("r"),
        help="Read full JSON dashboard spec from file or stdin (-)",
    )

    args = parser.parse_args()

    if args.input:
        spec = json.load(args.input)
    else:
        spec = {"title": args.title, "subtitle": args.subtitle, "sections": []}

        if args.agent:
            agent_rows = []
            for entry in args.agent:
                parts = [p.strip() for p in entry.split(",")]
                while len(parts) < 3:
                    parts.append("")
                agent_rows.append(parts[:3])
            if agent_rows:
                spec["sections"].append({"header": "STATUS", "rows": agent_rows})

        if args.queue:
            queue_rows = args.queue[:]
            if queue_rows:
                spec["sections"].append({"header": "QUEUE", "rows": queue_rows})

        if args.stat:
            stat_rows = []
            for pair in args.stat:
                k, v = pair.split("=", 1) if "=" in pair else (pair, "")
                stat_rows.append([k.strip(), v.strip()])
            if stat_rows:
                spec["sections"].append({"header": "TODAY", "rows": stat_rows})

    push(spec)


if __name__ == "__main__":
    main()
